'use client';
import {useState} from 'react';
import {Button,Badge,Avatar,Card,Alert,Separator,Skeleton,Label,Kbd,Input,Textarea,Checkbox,RadioGroup,Switch,Slider,Field,InputGroup,Select,Combobox,Accordion,Tabs,Collapsible,Breadcrumb,Pagination,Progress,Spinner,EmptyState,Table,DataTable,Dialog,AlertDialog,Drawer,Sheet,Popover,Tooltip,Dropdown,ContextMenu,HoverCard,NavigationMenu,Sidebar,Toggle,ToggleGroup,NumberField,Command,Calendar,DatePicker,Toast,FileUpload} from './index';
function ButtonDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Button>Continue</Button></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function BadgeDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Badge variant="success">Active</Badge></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function AvatarDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Avatar name="Alex Morgan"/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function CardDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Card title="Project settings" description="Make this workspace your own.">Your content goes here.</Card></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function AlertDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Alert title="Everything is up to date." variant="success">Your changes have been saved.</Alert></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function SeparatorDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><div>Account<Separator/>Preferences</div></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function SkeletonDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><div style={{width:240,display:"grid",gap:12}}><Skeleton style={{height:20,width:"60%"}}/><Skeleton style={{height:80}}/></div></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function LabelDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><div><Label htmlFor="label-demo">Full name</Label><input id="label-demo" className="cr-input"/></div></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function KbdDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><span>Open search <Kbd>⌘ K</Kbd></span></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function InputDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Input aria-label="Email address" type="email" placeholder="you@company.com"/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function TextareaDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Textarea aria-label="Project description" placeholder="Tell us about your project…"/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function CheckboxDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Checkbox label="Send me product updates" defaultChecked/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function RadioGroupDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><RadioGroup label="Plan" defaultValue="personal" options={[{value:"personal",label:"Personal"},{value:"team",label:"Team"}]}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function SwitchDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Switch label="Email notifications" defaultChecked/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function SliderDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Slider label="Volume" defaultValue={40} min={0} max={100}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function FieldDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Field label="Email" description="We’ll use this for account updates."><Input type="email" placeholder="you@company.com"/></Field></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function InputGroupDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><InputGroup aria-label="Website" leading="https://" placeholder="your-company.com"/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function SelectDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Select label="Timezone" defaultValue="paris" options={[{value:"paris",label:"Europe / Paris"},{value:"new-york",label:"America / New York"}]}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function ComboboxDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Combobox label="Framework" items={["React","Vue","Svelte","SolidJS"]}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function AccordionDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Accordion items={[{value:"ownership",title:"Do I own the code?",content:"Yes. Export it and use it in your own project."},{value:"runtime",title:"Does it need a server?",content:"The exported components run independently."}]}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function TabsDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Tabs label="Account" items={[{value:"profile",label:"Profile",content:"Your profile settings."},{value:"notifications",label:"Notifications",content:"Choose how you stay informed."}]}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function CollapsibleDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Collapsible title="Advanced options">Additional settings for this workspace.</Collapsible></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function BreadcrumbDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Breadcrumb items={[{label:"Workspace",href:"#workspace"},{label:"Settings",href:"#settings"},{label:"Profile"}]}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function PaginationDemo(){const [page,setPage]=useState(2);const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Pagination page={page} totalPages={8} onPageChange={setPage}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function ProgressDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Progress label="Upload progress" value={65}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function SpinnerDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Spinner label="Loading your workspace"/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function EmptyStateDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><EmptyState title="No projects yet" description="Create your first project to get started." action={<Button>Create project</Button>}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function TableDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Table caption="Team members" columns={["Name","Role"]} rows={[["Alex Morgan","Owner"],["Sam Taylor","Developer"]]}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function DataTableDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><DataTable caption="Projects" columns={[{key:"name",label:"Name"},{key:"status",label:"Status"}]} rows={[{name:"Website",status:"Active"},{name:"Mobile app",status:"Planning"}]}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function DialogDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Dialog trigger="Open dialog" title="Workspace settings" description="Manage the details of your workspace."><Input aria-label="Workspace name" placeholder="Acme"/></Dialog></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function AlertDialogDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><AlertDialog trigger="Open alertdialog" title="Workspace settings" description="Manage the details of your workspace."><Input aria-label="Workspace name" placeholder="Acme"/></AlertDialog></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function DrawerDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Drawer trigger="Open drawer" title="Workspace settings" description="Manage the details of your workspace."><Input aria-label="Workspace name" placeholder="Acme"/></Drawer></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function SheetDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Sheet trigger="Open sheet" title="Workspace settings" description="Manage the details of your workspace."><Input aria-label="Workspace name" placeholder="Acme"/></Sheet></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function PopoverDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Popover trigger="Set dimensions" title="Dimensions"><Input aria-label="Width" placeholder="Width"/></Popover></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function TooltipDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Tooltip trigger="Save" content="Save your changes to this library"/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function DropdownDemo(){const [notice,setNotice]=useState('');return <div className="cr-demo"><div><Dropdown trigger="Project actions" items={[{label:"Rename",onSelect:()=>setNotice(String("Rename")+" selected")},{label:"Archive",onSelect:()=>setNotice(String("Archive")+" selected")} ]}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function ContextMenuDemo(){const [notice,setNotice]=useState('');return <div className="cr-demo"><div><ContextMenu items={[{label:"Open",onSelect:()=>setNotice(String("Open")+" selected")},{label:"Duplicate",onSelect:()=>setNotice(String("Duplicate")+" selected")}]}>Right-click here, or press Shift + F10.</ContextMenu></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function HoverCardDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><HoverCard label="@alex" href="#profile"><strong>Alex Morgan</strong><p className="cr-description">Designer and developer.</p></HoverCard></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function NavigationMenuDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><NavigationMenu items={[{label:"Product",links:[{label:"Overview",href:"#overview",description:"Explore the platform."},{label:"Components",href:"#components"}]}]}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function SidebarDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Sidebar brand="Acme" items={[{label:"Overview",href:"#overview",active:true},{label:"Projects",href:"#projects"},{label:"Settings",href:"#settings"}]}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function ToggleDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Toggle aria-label="Bold text">B</Toggle></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function ToggleGroupDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><ToggleGroup label="Text alignment" items={[{value:"left",label:"Left"},{value:"center",label:"Center"},{value:"right",label:"Right"}]}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function NumberFieldDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><NumberField label="Team size" defaultValue={5} min={1} max={100}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function CommandDemo(){const [notice,setNotice]=useState('');return <div className="cr-demo"><div><Command items={[{value:"settings",label:"Open settings",onSelect:()=>setNotice(String("Settings")+" selected")},{value:"export",label:"Export library",onSelect:()=>setNotice(String("Export")+" selected")}]} /></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function CalendarDemo(){const [notice,setNotice]=useState('');return <div className="cr-demo"><div><Calendar defaultValue="2026-09-17" onValueChange={date=>setNotice(String(date)+" selected")}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function DatePickerDemo(){const [notice,setNotice]=useState('');return <div className="cr-demo"><div><DatePicker label="Due date" defaultValue="2026-09-17" onValueChange={date=>setNotice(String(date)+" selected")}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function ToastDemo(){const [notice,_setNotice]=useState('');return <div className="cr-demo"><div><Toast/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
function FileUploadDemo(){const [notice,setNotice]=useState('');return <div className="cr-demo"><div><FileUpload label="Project attachment" onFileSelect={file=>setNotice(String(file.name)+" selected")}/></div>{notice&&<p role="status" className="cr-description" style={{marginTop:12}}>{notice}</p>}</div>}
export const componentDemos={"button":ButtonDemo,"badge":BadgeDemo,"avatar":AvatarDemo,"card":CardDemo,"alert":AlertDemo,"separator":SeparatorDemo,"skeleton":SkeletonDemo,"label":LabelDemo,"kbd":KbdDemo,"input":InputDemo,"textarea":TextareaDemo,"checkbox":CheckboxDemo,"radio-group":RadioGroupDemo,"switch":SwitchDemo,"slider":SliderDemo,"field":FieldDemo,"input-group":InputGroupDemo,"select":SelectDemo,"combobox":ComboboxDemo,"accordion":AccordionDemo,"tabs":TabsDemo,"collapsible":CollapsibleDemo,"breadcrumb":BreadcrumbDemo,"pagination":PaginationDemo,"progress":ProgressDemo,"spinner":SpinnerDemo,"empty-state":EmptyStateDemo,"table":TableDemo,"data-table":DataTableDemo,"dialog":DialogDemo,"alert-dialog":AlertDialogDemo,"drawer":DrawerDemo,"sheet":SheetDemo,"popover":PopoverDemo,"tooltip":TooltipDemo,"dropdown":DropdownDemo,"context-menu":ContextMenuDemo,"hover-card":HoverCardDemo,"navigation-menu":NavigationMenuDemo,"sidebar":SidebarDemo,"toggle":ToggleDemo,"toggle-group":ToggleGroupDemo,"number-field":NumberFieldDemo,"command":CommandDemo,"calendar":CalendarDemo,"date-picker":DatePickerDemo,"toast":ToastDemo,"file-upload":FileUploadDemo};
export function ComponentShowcase({slug}:{slug:string}){const Demo=componentDemos[slug as keyof typeof componentDemos];return Demo?<Demo/>:<p>Component unavailable.</p>}
